### ISSUE TITLE
Populating a Vector

### ISSUE THREAD

**Issue by BorisKourt** [igorw/edn#2]
Trying to figure out the best way to populate a vector.

Lets say I have a function `getItem($item)`, that returns a formatted `edn\Map();` object. I want to then call that function multiple times and fill a vector with the returned maps. What is the syntax for that?

``` php
$allItems = new edn\Vector();
foreach($items as $item) {
    $returnedMap = getItem($item);
    // What do I do to allItems here?
}
```

Thank you!

**Comment by igorw** [comment]
Yeah, there is no really good way to do this. I'd gladly accept a pull request on adding a `conj` method to the `Collection` class that returns a new collection with the values added.

**Comment by igorw** [comment]
Or you can just define your own `conj` function to do it in your code base.

**Comment by BorisKourt** [comment]
Wish I had a bit more experience to contribute one, alas I think I am not up to par with both EDN and PHP. 

That said this appears to just work (as long as everything is a proper edn\map:)

``` php
function cards($posts) {
    $results = array();

    foreach($posts as $mypost) {
        $results[] = singleCard($mypost);
    }

    $cards = new edn\Vector($results);
    return $cards;
}
```

**Comment by igorw** [comment]
Yep, pre-building the array works as well of course :)

**Comment by igorw** [comment]
I'm trying to keep this library mostly about serialization and not try to add an entire collections library to it, so that's actually probably the better approach.

**Comment by BorisKourt** [comment]
I like how light weight it is, was able to get a hang of 99% of it after just an hour of hacking up a demo app. :) 

Working on setting up OM frontend rendering with a PHP backend right now.
